### ISSUE TITLE
Some dictionaries are not available

### ISSUE THREAD

**Issue by regisb** [dr-leo/PyHyphen#1]
As per https://groups.google.com/forum/#!topic/pyhyphen/UF4JFCG5V4A

Many languages seem to be now unavailable. This issue can be reproduced by running the following piece of code:

```
from hyphen import dictools
from hyphen.dictools import *

for lang in dictools.LANGUAGES:
    install(lang)

print(list_installed())
```

Error is:

```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    install(lang)
  File "/home/data/regis/projets/code/pyhyphen/hyphen/dictools.py", line 165, in install
    dict_url, locales = find_dictionary_location(repos, language)
  File "/home/data/regis/projets/code/pyhyphen/hyphen/dictools.py", line 202, in find_dictionary_location
    'Cannot find hyphenation dictionary for language ' + language + '.')
OSError: Cannot find hyphenation dictionary for language an_ES.
```

**Comment by dr-leo** [comment]
In v4.0.0 I have re-constructed the list of languages by scraping the repo with BeautifulSoup4. Still, some languages thus obtained do not work, e.g., 'fr'. The heuristics applied by dictools.install() does not seem to cover all cases where the subdir name differs from the .dict filename's locale string etc. A perfect solution would scrape all dictionaries.xcu files, collect all locales found therein for a particular .dict file and store the mappings in a local json file. Note that a single .dict file may cover multiple locales according to the corresponding .xcu file.
Having said that, I leave this issue open, leaving it to others to propose a solution if needed. As a workaround, users may manually download a desired dict and add it manually to the installed ones. However, this requires some effort to browse the repo, which is not documented.

**Comment by dr-leo** [comment]
I think this is obsolete. Any improvements on dict retrieval are welcome.
