### ISSUE TITLE
Ditch Appveyor in favour of Gihub actions

### ISSUE THREAD

**Issue by regisb** [dr-leo/PyHyphen#2]
Github actions is a recently-released CI/CD framework that provides Linux, Mac OS and Windows builds: https://github.com/features/actions

I suggest we migrate away from Appveyor and instead start using Githuib Actions. The reason for this move is that it's difficult to administer Appveyor from two different accounts. Also, I'd like to learn how to use github actions ;)

@dr-leo what do you think?

**Comment by dr-leo** [comment]
Agreed.

**Comment by dr-leo** [comment]
See #5
